CREATE TABLE TB_REPORT_SHIPMENTS (
    shipment_id VARCHAR2(100) NOT NULL,
    service_type VARCHAR2(50) NOT NULL,
    current_status VARCHAR2(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered_at TIMESTAMP WITH TIME ZONE,
    lead_time_minutes NUMBER(10, 2),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_REPORT_SHIPMENTS PRIMARY KEY (shipment_id)
);

CREATE INDEX IDX_REPORT_SHIPMENTS_CREATED ON TB_REPORT_SHIPMENTS (created_at);
CREATE INDEX IDX_REPORT_SHIPMENTS_STATUS ON TB_REPORT_SHIPMENTS (current_status);
CREATE INDEX IDX_REPORT_SHIPMENTS_SERVICE ON TB_REPORT_SHIPMENTS (service_type);
