-- =======================================================
-- Flyway Migration V1: Schema Initialization for Catalog
-- Domain: ms-rutaexpress-catalog (Oracle 23 & H2 Compatible)
-- =======================================================

-- 1. Tabla de Servicios de Catálogo
CREATE TABLE catalog_services (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL UNIQUE,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    category VARCHAR2(30) NOT NULL,
    status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    estimated_delivery_hours NUMBER(10) DEFAULT 24 NOT NULL,
    base_price NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
    price_per_km NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
    price_per_kg NUMBER(12, 2) DEFAULT 0.0 NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_services_code ON catalog_services(code);
CREATE INDEX idx_services_status ON catalog_services(status);
CREATE INDEX idx_services_category ON catalog_services(category);

-- 2. Tabla de Capacidad de Flota por Servicio y Zona
CREATE TABLE fleet_capacities (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id NUMBER(19) NOT NULL,
    zone VARCHAR2(30) NOT NULL,
    vehicle_type VARCHAR2(30) NOT NULL,
    max_daily_packages NUMBER(10) NOT NULL,
    current_booked_packages NUMBER(10) DEFAULT 0 NOT NULL,
    max_weight_kg NUMBER(10, 2) NOT NULL,
    max_volume_m3 NUMBER(10, 2) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_capacity_service FOREIGN KEY (service_id) REFERENCES catalog_services (id) ON DELETE CASCADE,
    CONSTRAINT uq_capacity_service_zone_veh UNIQUE (service_id, zone, vehicle_type)
);

CREATE INDEX idx_capacity_service ON fleet_capacities(service_id);
CREATE INDEX idx_capacity_zone ON fleet_capacities(zone);

-- 3. Tabla de Tarifas Zonales
CREATE TABLE tariffs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id NUMBER(19) NOT NULL,
    origin_zone VARCHAR2(30) NOT NULL,
    destination_zone VARCHAR2(30) NOT NULL,
    base_fare NUMBER(12, 2) NOT NULL,
    per_km_rate NUMBER(12, 2) NOT NULL,
    per_kg_rate NUMBER(12, 2) NOT NULL,
    min_fare NUMBER(12, 2) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_tariff_service FOREIGN KEY (service_id) REFERENCES catalog_services (id) ON DELETE CASCADE,
    CONSTRAINT uq_tariff_zones UNIQUE (service_id, origin_zone, destination_zone)
);

CREATE INDEX idx_tariff_service ON tariffs(service_id);
CREATE INDEX idx_tariff_zones ON tariffs(origin_zone, destination_zone);

-- =======================================================
-- Datos Semilla Iniciales (Seed Data)
-- =======================================================

-- Servicios Base
INSERT INTO catalog_services (code, name, description, category, status, estimated_delivery_hours, base_price, price_per_km, price_per_kg, active)
VALUES ('SRV-EXP-01', 'RutaExpress Mismo Día', 'Entrega urgente express garantizada en el mismo día dentro del radio urbano.', 'SAME_DAY', 'ACTIVE', 6, 4500.00, 350.00, 150.00, 1);

INSERT INTO catalog_services (code, name, description, category, status, estimated_delivery_hours, base_price, price_per_km, price_per_kg, active)
VALUES ('SRV-STD-01', 'RutaExpress Estándar 24h', 'Servicio logístico programado con entrega puerta a puerta en 24 a 48 horas.', 'STANDARD', 'ACTIVE', 24, 2800.00, 200.00, 100.00, 1);

INSERT INTO catalog_services (code, name, description, category, status, estimated_delivery_hours, base_price, price_per_km, price_per_kg, active)
VALUES ('SRV-FRG-01', 'RutaExpress Cuidado Especial', 'Despacho con embalaje reforzado y trazabilidad para paquetería frágil.', 'FRAGILE', 'ACTIVE', 24, 5500.00, 400.00, 250.00, 1);

-- Capacidades de Flota para SRV-EXP-01 (id 1)
INSERT INTO fleet_capacities (service_id, zone, vehicle_type, max_daily_packages, current_booked_packages, max_weight_kg, max_volume_m3, active)
VALUES (1, 'URBAN_CENTER', 'MOTORCYCLE', 60, 15, 15.00, 0.08, 1);

INSERT INTO fleet_capacities (service_id, zone, vehicle_type, max_daily_packages, current_booked_packages, max_weight_kg, max_volume_m3, active)
VALUES (1, 'URBAN_CENTER', 'VAN', 120, 40, 500.00, 3.50, 1);

INSERT INTO fleet_capacities (service_id, zone, vehicle_type, max_daily_packages, current_booked_packages, max_weight_kg, max_volume_m3, active)
VALUES (1, 'URBAN_PERIPHERY', 'VAN', 80, 20, 500.00, 3.50, 1);

-- Capacidades de Flota para SRV-STD-01 (id 2)
INSERT INTO fleet_capacities (service_id, zone, vehicle_type, max_daily_packages, current_booked_packages, max_weight_kg, max_volume_m3, active)
VALUES (2, 'URBAN_CENTER', 'VAN', 200, 50, 800.00, 5.00, 1);

INSERT INTO fleet_capacities (service_id, zone, vehicle_type, max_daily_packages, current_booked_packages, max_weight_kg, max_volume_m3, active)
VALUES (2, 'URBAN_PERIPHERY', 'TRUCK', 150, 30, 2500.00, 15.00, 1);

-- Tarifas para SRV-EXP-01
INSERT INTO tariffs (service_id, origin_zone, destination_zone, base_fare, per_km_rate, per_kg_rate, min_fare, active)
VALUES (1, 'URBAN_CENTER', 'URBAN_CENTER', 4500.00, 300.00, 120.00, 4500.00, 1);

INSERT INTO tariffs (service_id, origin_zone, destination_zone, base_fare, per_km_rate, per_kg_rate, min_fare, active)
VALUES (1, 'URBAN_CENTER', 'URBAN_PERIPHERY', 6000.00, 450.00, 180.00, 6000.00, 1);

-- Tarifas para SRV-STD-01
INSERT INTO tariffs (service_id, origin_zone, destination_zone, base_fare, per_km_rate, per_kg_rate, min_fare, active)
VALUES (2, 'URBAN_CENTER', 'URBAN_CENTER', 2800.00, 200.00, 80.00, 2800.00, 1);

INSERT INTO tariffs (service_id, origin_zone, destination_zone, base_fare, per_km_rate, per_kg_rate, min_fare, active)
VALUES (2, 'URBAN_CENTER', 'URBAN_PERIPHERY', 3800.00, 250.00, 100.00, 3800.00, 1);
